services:
  - type: web
    name: scoretracker
    runtime: python
    plan: free
    branch: main
    buildCommand: "./build.sh"
    startCommand: "cd scoretracker && gunicorn scoretracker.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: intramuralsscoretracker.onrender.com,localhost,127.0.0.1
      - key: CLOUDINARY_CLOUD_NAME
        value: dwiynqoyd
      - key: CLOUDINARY_API_KEY
        value: "628443394577536"
      - key: CLOUDINARY_API_SECRET
        value: IPwWMyr8WCX8WsJg8FHE_rmvjJ8
      - key: DJANGO_SUPERUSER_USERNAME
        value: admin
      - key: DJANGO_SUPERUSER_EMAIL
        value: admin@example.com
      - key: DJANGO_SUPERUSER_PASSWORD
        value: YourSecurePassword123!
    autoDeploy: true
